language: go
env:
  - GO111MODULE=on
branches:
  only:
    - main
go:
  - 1.15.x
  # go testing suite support was introduced in go 1.7, thus tests will only compile for go 1.7+.
  # Once we introduce TB.Helper() support (introduced in go 1.9), then tests will only run from go 1.9+.
script:
  - go test -coverprofile coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
